language: php

matrix:
  fast_finish: true
  include:
    - env: DM=~6.3
      php: hhvm
    - env: DM=~7.5
      php: 5.6
    - env: DM=~7.5
      php: 7
    - env: DM=~8.0
      php: 7.1
    - env: DM=@dev
      php: 7.2
  allow_failures:
    - env: DM=@dev

sudo: false

install: travis_retry composer require "wikibase/data-model=$DM" --prefer-source

# Hack: Don't run phpmd with HHVM
script: if $(php --version | grep -q HipHop); then composer test; else composer ci; fi

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
