language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DM=~4.2
      php: 5.3
    - env: DM=~4.2
      php: 5.4
    - env: DM=~4.3@dev
      php: 5.6
    - env: DM=~4.2
      php: 7
    - env: DM=~4.2
      php: hhvm
    - env: DM=@dev
      php: 5.6
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: DM=@dev

sudo: false

install: travis_retry composer require "wikibase/data-model=$DM" --prefer-source

script: composer ci

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
